### ISSUE TITLE
brew search warning: Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by ahrib** [sidneys/homebrew-homebrew#10]
Performing a brew search results in a warning message appearing on screen.

**to replicate**

    brew search test

**Result**

    Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
    Please report this issue to the sidneys/homebrew tap (not Homebrew/brew or Homebrew/core):
      /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew/Casks/sourcetree-latest.rb:10

**Expected result**
No warning to be shown

**System info**
Software:

    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 36 days 3:17

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.121.3
      OS Loader Version: 7459.121.3

**Comment by sidneys** [comment]
Hi @ahrib, thanks for your feedback 👏 

I removed the cask from the repository ([#a4af4e2](https://github.com/sidneys/homebrew-homebrew/commit/a4af4e2f748e644c00c68418efab286c1e1e15e6)), as the related application (a "Latest" variant of Sourcetree) has not been updated in some time.

Cheers, 
S
