### ISSUE TITLE
Looking for "sidneys/homebrew/chntpw"

### ISSUE THREAD

**Issue by mattpackwood** [sidneys/homebrew-homebrew#13]
I was looking to clean up after using some of your excellent tools, can you confirm what "`brew install sidneys/homebrew/chntpw`" installs?

Matt

**Comment by sidneys** [comment]
Hi @mattpackwood,

thanks for the accolades, you're welcome 😊 

I just tried reinstalling `chntpw` without issues, however, changes were required to satisfy Homebrew's updated stylistic guidelines, which were just pushed (https://github.com/sidneys/homebrew-homebrew/commit/f9482e0b18c800c800081e9ab1bb0968913606ab).

If the problem persists, please keep me updated.

Cheers,
S

**Comment by mattpackwood** [comment]
@sidneys I was looking for a list of that it installs?

**Comment by freebrowser1** [comment]
Does not work on macOS Intel anymore.
On a Mac M1 it does work, so it is an Intel issue.

```userpc:~/scratch % brew install sidneys/homebrew/chntpw
==> Downloading https://github.com/sidneys/chntpw/archive/0.99.6.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/dee692592b6fc0d6db43012210cf70e9ef7a6018e20818b5f15187cbd3a06e39--chntpw-0.99.6.tar.gz
==> Installing chntpw from sidneys/homebrew
==> make
Last 15 lines from /Users/user/Library/Logs/Homebrew/chntpw/01.make:
2022-12-07 12:39:49 +0000

make

gcc -c -DUSEOPENSSL -g -I. -I/usr/local/opt/openssl/include -Wl chntpw.c
gcc -c -DUSEOPENSSL -g -I. -I/usr/local/opt/openssl/include -Wl ntreg.c
gcc -c -DUSEOPENSSL -g -I. -I/usr/local/opt/openssl/include -Wl edlib.c
gcc -c -DUSEOPENSSL -g -I. -I/usr/local/opt/openssl/include -Wl cpnt.c
gcc -c -DUSEOPENSSL -g -I. -I/usr/local/opt/openssl/include -Wl reged.c
gcc -DUSEOPENSSL -g -I. -I/usr/local/opt/openssl/include -Wl -o cpnt cpnt.o -L/usr/local/opt/openssl/lib /usr/local/opt/openssl/lib/libcrypto.a
clang: error: no such file or directory: '/usr/local/opt/openssl/lib/libcrypto.a'
make: *** [cpnt] Error 1
make: *** Waiting for unfinished jobs....

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Looking for "sidneys/homebrew/chntpw" https://github.com/sidneys/homebrew-homebrew/issues/13
Mac M1 chntpw not building (Openssl 1.0 requirement not satisfied) https://github.com/sidneys/homebrew-homebrew/issues/2
userpc:~/scratch % 
```

**Comment by thales-man** [comment]
doesn't build on an M1 pro
==> Applying openssl-1.0.2u-darwin-arm64.patch
patching file Configure
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2u_1 --openssldir=/opt/homebrew/etc/openssl@1.0 no-ssl2 no-ss
==> make
==> make test
Last 15 lines from /Users/colin/Library/Logs/Homebrew/openssl@1.0/03.make:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8670419948:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
8670419948:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
8670419948:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
make[1]: *** [test_ec] Error 1
make: *** [tests] Error 2

**Comment by nandy6666** [comment]
$ brew tap minacle/chntpw
$ brew install aria2 cabextract wimlib cdrtools minacle/chntpw/chntpw

**Comment by mattpackwood** [comment]
Original issue addressed.
