### ISSUE TITLE
Error in webstorm-eap definition

### ISSUE THREAD

**Issue by orkisz** [sidneys/homebrew-homebrew#31]
When searching for any formula, following error appears:

```
Error: Cask 'webstorm-eap' definition is invalid: 'appcast' stanza failed with: Calling the `appcast` stanza is disabled! Use the `livecheck` stanza instead.
Please report this issue to the sidneys/homebrew tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew/Casks/webstorm-eap.rb:6
```

For now, only way to move forward is to temporarily untap `sidneys/homebrew`

**Comment by sidneys** [comment]
Hi @orkisz 

Thanks! The `webstorm-eap` cask has been updated, including new definitions for ARM.

https://github.com/sidneys/homebrew-homebrew/commit/a5470f71f497ec9b80d7c82dea1bb6ac9e35f458

Cheers,
S
