### ISSUE TITLE
Depreciated value for depends_on in sourcetree Cask

### ISSUE THREAD

**Issue by leftl** [sidneys/homebrew-homebrew#9]
Encountered the following warning when searching for a cask:
```
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the sidneys/homebrew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/sidneys/homebrew-homebrew/Casks/sourcetree-latest.rb:10
```

Looks like the version symbol must be bumped to `el_capitan`, per [documentation](https://docs.brew.sh/Cask-Cookbook#depends_on-macos). It is worth noting that nothing is broken, however. Thanks for maintaining this tap!

**Comment by solus-hq** [comment]
Same here, is it easily fixable?

**Comment by LostInCompilation** [comment]
Can confirm, same warning.

**Comment by sidneys** [comment]
Hi @leftl, thanks for the heads-up

The cask has been removed from the tap due to the application being outdated (https://github.com/sidneys/homebrew-homebrew/commit/a4af4e2f748e644c00c68418efab286c1e1e15e6).

Cheers,
S
